### ISSUE TITLE
Setup packages for semver

### ISSUE THREAD

**Issue by fhightower** [democritus-project/roadmap#69]
- [x] ~Update version numbers (handled by #50)~
- [x] ~Add badge (handled by #62)~
- [x] ~Update github action to deploy to pypi (handled by #50)~
- [x] Add bumpversion as requirement (and add docker commands to use it (see https://github.com/ioc-fang/ioc-fanger/commit/21b2bf256ebf981d5143685b43d6d56724c4e2a0 and https://github.com/ioc-fang/ioc-fanger/commit/160c6f9ed4ca9622e3df3825623e3dc9d0ee14ed))
- [x] Store version info in setup.cfg
- [x] Update __init__.py to have simple version info
- [x] Deploy to pypi
